### ISSUE TITLE
Pull requests here won’t count toward Hacktoberfest.

### ISSUE THREAD

**Issue by hacktoberfest-team** [illacceptanything/illacceptanything#988]
Hi there,

Thanks for your interest in Hacktoberfest and helping others learn how to make their first contributions to open source!

That said, high-quality contributions are part of the [the core values of Hacktoberfest](https://hacktoberfest.digitalocean.com/details), so we kindly ask that you do not create repositories which allow users to quickly gain a PR toward completing the challenge.

We encourage you to take a look at our list of [Hacktoberfest issues](https://hacktoberfest.digitalocean.com/#projects) for inspiration and ideas about making meaningful contributions to open source projects.

_Due to this, we've added this repository to our list of excluded repositories and pull requests here will not count toward Hacktoberfest 2019._

Please note, you are welcome to keep running this repository as a learning tool for new contributors to open-source, but pull requests won’t count toward Hacktoberfest.

Happy Hacking,
The Hacktoberfest Team

Hacktoberfest is presented by [DigitalOcean](https://do.co/hacktoberfest50) and [DEV](https://dev.to).

**Comment by ProgVal** [comment]
Hello,

Thank you for your interest in illacceptanything and helping others learn how to make their first contributions to open source!

That said, funny contributions are part of the the core values of illacceptanything; and every october this repo gets a spam of trivial pull-requests from people who want to get a free t-shirt.
So we kindly asked you (see email titled `Low-effort PRs to the "illacceptanything" repository` sent on 2017-10-15) that you do not encourage users to use this repo to quickly gain a PR toward completing the challenge. Your answer (on 2017-10-19) was that you couldn't do anything on your end, and we had to tag all such PRs as "invalid", which we did.

We encourage you to take a look at [our list of invalid pull requests](https://github.com/illacceptanything/illacceptanything/pulls?utf8=%E2%9C%93&q=label%3Ainvalid) for inspiration and ideas about non-meaningful contributions to our open source projects we received.

Due to this, we're glad you added this repository to your list of excluded repositories and pull requests that will not count toward Hacktoberfest 2019.

Please note, you are welcome to keep running this event as a learning tool for new contributors to open-source, as long as pull requests here won’t count toward Hacktoberfest.

Happy Hacking,
illacceptanything

**Comment by jlu5** [comment]
@hacktoberfest-team @digitalocean In all seriousness this repo was designed as a social experiment, and not at all with Hacktoberfest in mind. Please don't blame us for people wanting to game the system to begin with - we're just as disappointed by the spam as you are.
